// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw6TME4yV46e5lWtDUuGD24pKoZWYNxEs',
    appId: '1:942066822670:web:4f3cc4fed98b620689965f',
    messagingSenderId: '942066822670',
    projectId: 'doctor-hunt-14df5',
    authDomain: 'doctor-hunt-14df5.firebaseapp.com',
    storageBucket: 'doctor-hunt-14df5.firebasestorage.app',
    measurementId: 'G-P1LSTDB675',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7xKZC4S9bOpscWWP57nNfYUWBGBUztkg',
    appId: '1:942066822670:android:db23ae06e415c62189965f',
    messagingSenderId: '942066822670',
    projectId: 'doctor-hunt-14df5',
    storageBucket: 'doctor-hunt-14df5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyHEBXYO1VwhxcR-P-J1Z-AOiOmMR1X3A',
    appId: '1:942066822670:ios:646bcefa489949e389965f',
    messagingSenderId: '942066822670',
    projectId: 'doctor-hunt-14df5',
    storageBucket: 'doctor-hunt-14df5.firebasestorage.app',
    iosBundleId: 'com.example.doctorHunt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyHEBXYO1VwhxcR-P-J1Z-AOiOmMR1X3A',
    appId: '1:942066822670:ios:646bcefa489949e389965f',
    messagingSenderId: '942066822670',
    projectId: 'doctor-hunt-14df5',
    storageBucket: 'doctor-hunt-14df5.firebasestorage.app',
    iosBundleId: 'com.example.doctorHunt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw6TME4yV46e5lWtDUuGD24pKoZWYNxEs',
    appId: '1:942066822670:web:ceb1879a9814117689965f',
    messagingSenderId: '942066822670',
    projectId: 'doctor-hunt-14df5',
    authDomain: 'doctor-hunt-14df5.firebaseapp.com',
    storageBucket: 'doctor-hunt-14df5.firebasestorage.app',
    measurementId: 'G-DX2CJT3W7E',
  );
}
